/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesRefRouteImport } from './routes/mes.$ref'

const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesRefRoute = MesRefRouteImport.update({
  id: '/mes/$ref',
  path: '/mes/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/relatorio': typeof RelatorioRoute
  '/mes/$ref': typeof MesRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/relatorio': typeof RelatorioRoute
  '/mes/$ref': typeof MesRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/relatorio': typeof RelatorioRoute
  '/mes/$ref': typeof MesRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracoes' | '/relatorio' | '/mes/$ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracoes' | '/relatorio' | '/mes/$ref'
  id: '__root__' | '/' | '/configuracoes' | '/relatorio' | '/mes/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  RelatorioRoute: typeof RelatorioRoute
  MesRefRoute: typeof MesRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes/$ref': {
      id: '/mes/$ref'
      path: '/mes/$ref'
      fullPath: '/mes/$ref'
      preLoaderRoute: typeof MesRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  RelatorioRoute: RelatorioRoute,
  MesRefRoute: MesRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
